### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by zabbal** [Quasilyte/repolint#19]
go get -v github.com/Quasilyte/repolint 
...
github.com/gomarkdown/markdown/parser
github.com/Quasilyte/repolint
# github.com/Quasilyte/repolint
../go/src/github.com/Quasilyte/repolint/utils.go:32:22: error: reference to undefined identifier ‘data.ContentMatchers’
  matcher, ok := data.ContentMatchers[ext]
                      ^
../go/src/github.com/Quasilyte/repolint/utils.go:32:2: error: expected map index on right hand side
  matcher, ok := data.ContentMatchers[ext]
  ^
../go/src/github.com/Quasilyte/repolint/utils.go:32:2: error: invalid tuple definition

go version
go version go1.10.3 gccgo (Ubuntu 8.3.0-6ubuntu1) 8.3.0 linux/amd64

**Comment by quasilyte** [comment]
I'll take a look, thank you for reporting.

**Comment by quasilyte** [comment]
Should be fixed now.
